/* This file is autogenerated.  Do not edit. */

#include "v3dv_drirc.h"

static const driOptionDescription dri_options[] = {
DRI_CONF_SECTION("Debugging")
   DRI_CONF_OPT_B(vk_wsi_force_bgra8_unorm_first
      , false
      , "Force vkGetPhysicalDeviceSurfaceFormatsKHR to return VK_FORMAT_B8G8R8A8_UNORM as the first format"
      )
   DRI_CONF_OPT_B(vk_wsi_force_swapchain_to_current_extent
      , false
      , "Force VkSwapchainCreateInfoKHR::imageExtent to be VkSurfaceCapabilities2KHR::currentExtent"
      )
   DRI_CONF_OPT_B(vk_wsi_disable_unordered_submits
      , false
      , "Disable unordered WSI submits to workaround application synchronization bugs"
      )
   DRI_CONF_OPT_B(vk_x11_ignore_suboptimal
      , false
      , "Force the X11 WSI to never report VK_SUBOPTIMAL_KHR"
      )
DRI_CONF_SECTION_END
DRI_CONF_SECTION("Performance")
   DRI_CONF_OPT_B(adaptive_sync
      , true
      , "Adapt the monitor sync to the application performance (when possible)"
      )
   DRI_CONF_OPT_I(vk_x11_override_min_image_count
      , 0
      , 0
      , 999
      , "Override the VkSurfaceCapabilitiesKHR::minImageCount (0 = no override)"
      )
   DRI_CONF_OPT_B(vk_x11_strict_image_count
      , false
      , "Force the X11 WSI to create exactly the number of image specified by the application in VkSwapchainCreateInfoKHR::minImageCount"
      )
   DRI_CONF_OPT_B(vk_x11_ensure_min_image_count
      , false
      , "Force the X11 WSI to create at least the number of image specified by the driver in VkSurfaceCapabilitiesKHR::minImageCount"
      )
   DRI_CONF_OPT_B(vk_xwayland_wait_ready
      , true
      , "Wait for fences before submitting buffers to Xwayland"
      )
DRI_CONF_SECTION_END
DRI_CONF_SECTION("Misc")
   DRI_CONF_OPT_F(heap_memory_percent
      , 0.0
      , 0.0
      , 1.0
      , "Percentage of total system memory to report as gpu heap memory (0 = driver default)"
      )
DRI_CONF_SECTION_END
};

void
v3dv_parse_dri_options(struct v3dv_drirc *drirc,
                                   const driConfigFileParseParams *params)
{
   driParseOptionInfo(&drirc->available_options, dri_options, ARRAY_SIZE(dri_options));
   driParseConfigFiles(&drirc->options, &drirc->available_options, params);

   drirc->misc.heap_memory_percent = driQueryOptionf(&drirc->options, "heap_memory_percent");
}
