/* This file is autogenerated.  Do not edit. */

#ifndef V3DV_DRIRC_H
#define V3DV_DRIRC_H

#ifdef __cplusplus
extern "C" {
#endif

#include "util/driconf.h"

struct v3dv_drirc {
   struct driOptionCache options;
   struct driOptionCache available_options;

   struct {
      float heap_memory_percent;
   } misc;
};

void v3dv_parse_dri_options(struct v3dv_drirc *drirc,
                                        const driConfigFileParseParams *params);

#ifdef __cplusplus
}
#endif

#endif /* V3DV_DRIRC_H */
